### ISSUE TITLE
Integration with typescript 

### ISSUE THREAD

**Issue by IIIristraM** [styled-components/babel-plugin-styled-components#41] opened 2017-04-11 14:45 UTC
I'm using babel to transpile ES6 made by typescript to ES5. And it looks like this plugin doesn't work at all in this case.

typescript v2.2.2
styled-components v2.0.0-15
awesome-typescript-loader v3.1.2
babel-plugin-styled-components v1.1.4

**Comment by philpl** [comment] 2017-04-11 15:29
@IIIristraM The awesome-typescript-loader has support to trigger a babel transpilation as well. The option is called `useBabel`.

https://github.com/s-panferov/awesome-typescript-loader#usebabel-boolean-defaultfalse

It's not something we can do on our side, since it's a build pipeline problem ;)

**Comment by IIIristraM** [comment] 2017-04-11 16:50
Well I found one place where plugin was applied, so at least it takes part in a build process.  And I'm going to disagree with you.

This is output from the same file

```
var LoginButton = styles_1.styled.div(_templateObject, function (props) {
    return props.theme.mainColor;
});
function xxx(styled) {
    var XXX = styled.div.withConfig({
        displayName: "login__XXX"
    })([""]);
}
```
So the place with import was skipped, while the function where was string like  `const XXX = styled.div``;` was processed. It looks like parsing issue, so I suppose it's responsibility of the plugin.

**Comment by philpl** [comment] 2017-04-11 18:44
@IIIristraM Hm, I was thinking maybe TypeScript transpiles the above LoginButton tagged template literal and thus the babel plugin doesn't find any template literals anymore. However, the second one is indeed being transpiled.

Can you provide your `.babelrc` and a test file, so I can find out what's going on? ;)

**Comment by IIIristraM** [comment] 2017-04-12 07:45
`.babelrc`
```
{
  "presets": [
    "es2015",
    "stage-0"
  ],
  "plugins": [
    "styled-components"
  ]
}
```

original file
```
import { styled } from 'styles';

const LoginButton = styled.div`
  display: block;
  width: 140px;
  height: 48px;
`;
```
output
```
var styles_1 = __webpack_require__("./app/scripts/styles/index.tsx");
var LoginButton = styles_1.styled.div(_templateObject, function (props) {
    return props.theme.mainColor;
});
```

`styles` file
```
import * as React from 'react';
import * as styledComponents from 'styled-components';
import { ThemedStyledComponentsModule, ThemeProps } from 'styled-components';
import { Theme } from 'types';

// -------------------------------CONFIG CUSTOM THEME----------------------------------------

const {
    default: styled,
    css,
    injectGlobal,
    keyframes,
    ThemeProvider,
} = styledComponents as ThemedStyledComponentsModule<Theme>;

export { css, injectGlobal, keyframes, ThemeProvider, ThemeProps, styled };

// ------------------------------------HELPERS-----------------------------------------------

export function styledWithProps<TProps>() {
  const Div = styled.div``; // This line will be transpliled correctly

  class Wrap extends React.PureComponent<TProps & React.HTMLProps<{}>, {}> {
    public node: HTMLElement;

    public render() {
      return <Div {...this.props} innerRef={n => this.node = n} />;
    }
  }

  return styled(Wrap);
}
```
output
```
var React = __webpack_require__("./node_modules/react/react.js");
var styledComponents = __webpack_require__("./node_modules/styled-components/dist/styled-components.es.js");
// -------------------------------CONFIG CUSTOM THEME----------------------------------------
var styled = styledComponents.default,
    css = styledComponents.css,
    injectGlobal = styledComponents.injectGlobal,
    keyframes = styledComponents.keyframes,
    ThemeProvider = styledComponents.ThemeProvider;

exports.styled = styled;
exports.css = css;
exports.injectGlobal = injectGlobal;
exports.keyframes = keyframes;
exports.ThemeProvider = ThemeProvider;
// ------------------------------------HELPERS-----------------------------------------------
function styledWithProps() {
    var Div = styled.div.withConfig({
        displayName: "styles__Div"
    })([""]);

    var Wrap = function (_React$PureComponent) {
        _inherits(Wrap, _React$PureComponent);

        function Wrap() {
            _classCallCheck(this, Wrap);

            return _possibleConstructorReturn(this, (Wrap.__proto__ || Object.getPrototypeOf(Wrap)).apply(this, arguments));
        }

        _createClass(Wrap, [{
            key: "render",
            value: function render() {
                var _this2 = this;

                return React.createElement(Div, Object.assign({}, this.props, { innerRef: function innerRef(n) {
                        return _this2.node = n;
                    } }));
            }
        }]);

        return Wrap;
    }(React.PureComponent);

    return styled(Wrap);
}
exports.styledWithProps = styledWithProps;
```

**Comment by vdanchenkov** [comment] 2017-04-26 15:30
@IIIristraM could you try to change original file to
```
import * as styles from 'styles';

const styled = styles.styled

const LoginButton = styled.div`
  display: block;
  width: 140px;
  height: 48px;
`;
```

And make sure you do not import 'styled-components' directly in this file.

If it works, we will know the source of the problem.

**Comment by IIIristraM** [comment] 2017-04-26 18:16
Yes, it works

**Comment by vdanchenkov** [comment] 2017-04-26 20:43
So the problem is that `styled.div` was converted to `styles_1.styled` before it got passed to the plugin. Probably it is done by the typescript, I'm not sure.

As a result, plugin failed to identify `styles_1.styled` as a styled component helper. We probably need to make the logic more vague, but not too much. 

I think that `some.name.styled.div`color: red` ` should not be considered a styled component. While `somename.styled.div` could be.

 @IIIristraM If you want to look into it, it's in the https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/utils/detectors.js#L16

Currently it correctly identifies following expressions:
```
styled.div``
styled.div.something``
styled(OtherComponent).something``
```

**Comment by philpl** [comment] 2017-04-28 16:36
@vdanchenkov I think we can solve that with the webpack plugin — once I actually get to writing it — since we want to run our transformations before typescript etc

**Comment by raphaelsaunier** [comment] 2017-05-01 10:32
I came to the same conclusions as @vdanchenkov after running into issues when using it with a next.js application.

Since, in this case, the [recommendation](https://github.com/zeit/next.js/tree/master/examples/with-typescript) is to first compile the TypeScript sources before letting Babel apply its transformations, it might be worth tweaking the detector after all?

**Comment by Igorbek** [comment] 2017-06-15 19:26
I'm currently working on a plugin for TypeScript that would do mostly the same as this one, so that typescript users don't need to use Babel (in most cases it's problematic). The prototype is working pretty well, however nothing is documented, that's next on the list: https://github.com/Igorbek/typescript-plugin-styled-components

**Comment by philpl** [comment] 2017-06-15 20:04
@Igorbek since in v3 we'll have a webpack plugin as well, this issue will be solved then as well. I don't see a lot of trouble anymore going forward with TS. Keep in mind? That the plugin will still need to be lean, since this plugin will probably be either mostly or fully replaced, depending on the implementation of the preprocessing. The library for that is planned to be compatible with other css-in-js libs as well

**Comment by Igorbek** [comment] 2017-06-15 20:38
@philpl interesting, where can I read plans/discussions about future plans for v3 and webpack plugin that would be helpful for TS users? I've heard of idea of css preprocessing and saving it into faster data structure. is that it?

**Comment by philpl** [comment] 2017-06-15 20:49
@Igorbek I'm going to touch base with Sunil tomorrow to actually discuss the preprocessor lib and it's spec. There's also a spec for a CSS AST for css-in-js :wink: https://github.com/cssinjs/standard/pull/17

Other than that there's not much yet.

We're already doing css preprocessing in this plugin, but we'll make it so that it can run during the runtime as well, making updates to components faster. The whole point is basically that the build-step and the run-time will be able to share the same code.

**Comment by huy-nguyen** [comment] 2017-06-21 20:51
I ran into this same problem and used @vdanchenkov's solution and it worked. However, today after upgrading to typescript 2.4 and changing the `module` option in `tsconfig.json` to `esnext`, this problem goes away i.e. `import styled from 'styled-components'` doesn't interfere with this babel plugin anymore.

**Comment by cryve** [comment] 2018-08-06 13:57
Thanks a lot @huy-nguyen! With `"module": "esnext"` in tsconfig.json I was able to get babel-plugin-styled-components to work with the following setup: 
* parcel-bundler 1.9.7
* typescript 3.0.1
* babel-plugin-styled-components 1.5.1

**Comment by kitten** [comment] 2018-08-06 15:27
Just as a quick note here, it’s now possible to run the Typescript checker separately and instead of using it to also transpilation one can nowbuse Babel which is a lot less tedious ✨  https://babeljs.io/docs/en/next/babel-preset-typescript.html

cc @probablyup: Should we close this and maybe file an issue to add this approach to the readme?

**Comment by probablyup** [comment] 2018-08-06 16:29
Yessssss

**Closed** 2018-08-06 21:02 UTC

**Comment by fbenedetti-zinio** [comment] 2018-09-19 07:17
Following the Microsoft post (https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/) the Typescript compiler is still the preferred solution over Babel. Indeed it would have a huge impact for our stack to migrate to babel (some of Typescript syntax is not even supported by the Babel compiler). Is there any chance to solve the issue without the need of configuring Babel?

**Comment by probablyup** [comment] 2018-09-19 13:55
The only non-babel integration is Igor’s TS plugin

**Comment by Igorbek** [comment] 2018-09-19 17:19
Here's it https://github.com/Igorbek/typescript-plugin-styled-components

**Comment by probablyup** [comment] 2018-09-19 17:20
Actually Igor is your plugin mentioned in the TS docs on the website?

**Comment by Igorbek** [comment] 2018-09-19 21:18
It is not. I can make PR to the docs site, if you don't mind.

**Comment by probablyup** [comment] 2018-09-19 21:18
Yes please!

**Comment by fbenedetti-zinio** [comment] 2018-09-20 10:40
Igor's plugin worked well on webpack, but I use directly the typescript compiler to transpile the server code. Is there any chance to set it up as plugin inside the tsconfig.json?

**Comment by cloutiertyler** [comment] 2018-09-21 23:03
@probablyup Is there no way to do it with just the class metadata alone, plus some randomness? As far as I can tell it's impossible to get debugging working with Typescript, StyledComponents, and SSR.

Even just a little hint at what classes the elements are would go a very long way.

**Comment by probablyup** [comment] 2018-09-21 23:04
Nope. We’ve tried. The only way to ensure total uniqueness is to also include file path in the hashing because they’re guaranteed to be unique. 

displayName + variable name combinations can collide relatively easily.

**Comment by probablyup** [comment] 2018-09-21 23:05
Unique and more importantly, stable.

**Comment by cloutiertyler** [comment] 2018-09-21 23:06
Thanks for the quick response! That's the pits though. :/

**Comment by cloutiertyler** [comment] 2018-09-21 23:13
@probablyup There's no way to hash the content of the styles to arrive at a unique class name is there? That would be both unique and stable, right? e.g. (MyComponent-<md5(width:100%)>)

Admittedly, I definitely don't know the full scope of the problem, so I'm kind of drive-by engineering here.

**Comment by probablyup** [comment] 2018-09-21 23:16
Not with dynamic styles from functions that could be coming from anywhere

**Comment by fabyo82** [comment] 2018-09-22 13:12
I'm trying to modify the Igor's plugin adding a componentId config. Would it work if I hash the file path and the content?

**Comment by fabyo82** [comment] 2018-09-28 08:45
I was able to setup SSR with typescript updating the Iogr's plugin.
I added the componentId to the withConfig, in a similar way the babel plugin works.
In addition, as I'm not using webpack for the server compilation, I found https://github.com/cevek/ttypescript to transpile using the same transformer.
I created a PR if anyone is interested.

**Comment by cloutiertyler** [comment] 2018-10-05 22:33
Just out of curiosity @probablyup, it looks like styled-components already chooses the name based on the content of the CSS of the component:

https://github.com/styled-components/styled-components/blob/5bddab8c0a3272c8b617600d10727c155224186d/src/models/ComponentStyle.js#L89

It just evaluates the dynamic rules and flattens the whole thing. What does the file path have to do with this again?

I'm sorry for all the questions, but I legitimately do not understand the need for the babel plugins or whether I need to compile my typescript with them for both the bundle I send to the client and also the compiled code I run in node JS. I cannot for the life of me figure out what the devil those plugins do. Why would transpiling the JS code for the client bundle change the output classNames of the code when run? What is the plugin actually changing to make the names consistent on the client and server?

**Comment by mxstbr** [comment] 2018-10-06 13:09
> it looks like styled-components already chooses the name based on the content of the CSS of the component:

@cloutiertyler yes, but that is the instance-specific class. Every component has two classes, one is the instance-specific one and one is shared between all instances of the same component. Unfortunately the hash will differ between different instances, so we need to create that shared class somehow else, and for that we need to know the name of the component, which JavaScript the language doesn't let us do. That's why we need a build-time transform.

See https://github.com/styled-components/styled-components/issues/2064#issuecomment-427571787 for more details.
