### ISSUE TITLE
Add Uglify Pure comments automatically

### ISSUE THREAD

**Issue by mxstbr** [styled-components/babel-plugin-styled-components#114] opened 2017-12-21 11:54 UTC
We should add `// #__PURE__` comments before every `css`, `styled` and `keyframes` call. This will let UglifyJS know that those functions are pure, so it can remove them if they are unused in the users application code. (essentially, better tree shaking)

This should have an option to be disabled for folks that are not using UglifyJS, probably call that option `uglify` which is set to true by default.

> Thanks to @mitchellhamilton for pointing this out, here's the code from the emotion Babel plugin: https://github.com/emotion-js/emotion/blob/b1db578003df11ddf578d07e191bc43964ef2af7/packages/babel-plugin-emotion/src/index.js#L210

**Comment by osamajandali** [comment] 2018-01-08 15:51
I will work on this.

**Comment by Andarist** [comment] 2018-01-09 14:49
@cameron-martin has created a package which should help with detecting imports https://github.com/cameron-martin/babel-helper-references-import

**Comment by osamajandali** [comment] 2018-01-10 10:44
@Andarist This is cool, I will give it a try.

**Comment by osamajandali** [comment] 2018-01-10 12:52
I have a little problem here..
when the function is assigned to a variable UglifyJS doesn't remove it, as you can see in the next snippet.
[https://i.imgur.com/f79JsSG.png](url) 

if we remove the variable it will work just fine.
[https://i.imgur.com/3v0nP5Z.png](url)

I know this is something related to uglifyjs but I just want to make sure that this is write thing to implement.

**Comment by osamajandali** [comment] 2018-01-10 13:17
As far as I understand the issue is that if we have this snippet:
![image](https://user-images.githubusercontent.com/13832392/34774441-023ce458-f618-11e7-8981-34f850e02673.png)
and we used babel-plugin-styled-components on it should output this:
![image](https://user-images.githubusercontent.com/13832392/34774519-501b213a-f618-11e7-8067-0d44cab8d03a.png)

and if you apply UglifyJS on it should remove the function by now.

The thing is when the function is assigned to a variable UglifyJS consider the function used (in our case it is assigned to **Button**) and didn't remove it.

Take a look here:
![image](https://user-images.githubusercontent.com/13832392/34774671-e2ab3238-f618-11e7-9c37-481ffb8b1006.png)

and when removing the assignment:
![image](https://user-images.githubusercontent.com/13832392/34774688-fe7e61ce-f618-11e7-82fe-464b19e5de4d.png)

I just wonder how this could help for a better tree shaking! 

P.S: also I have tried the same thing on emotion-js snippet and get the same output.

**Comment by mxstbr** [comment] 2018-01-10 13:25
Huh that's weird! @mitchellhamilton how are y'all doing this?!

**Comment by mitchellhamilton** [comment] 2018-01-10 13:33
I remember trying it with webpack (3 iirc) and it removed the call, I think the uglify option needed is `--pure-funcs`.

**Comment by philpl** [comment] 2018-01-10 13:41
@mitchellhamilton @mxstbr regarding webpack 3, that would totally depend on how it assumes that an imported function call is pure. I'm not sure how they're determining that right now.

**Comment by Andarist** [comment] 2018-01-10 13:44
`#__PURE__` is an uglifyJS thing and it has nothing to do with webpack.

Unfortunately webpack actually doesn't do complete tree-shaking, it just removes assignments to exports object and annotate the code with something like `/* unused harmony export */`. It's UglifyJS which does dead code elimination later (thanks to the fact that webpack has removed those exports assignments).

I think there should be no need for additional flag to make this work, usually just something like:
```sh
uglifyjs -mc passes=3,unsafe --toplevel
```
does the trick.

Let me check @osamajandali (TIP: next time please paste in your code, it will make way easier to just copy it 😉 ) examples and get back to you

**Comment by osamajandali** [comment] 2018-01-10 13:49
@mitchellhamilton I use uglifyjs cli without webpack, and I have tried --pure-funcs and it doesn't work.

**Comment by Andarist** [comment] 2018-01-10 13:49
@osamajandali which version of uglifyJS do you test?

with the command I gave above (`uglifyjs -mc passes=3,unsafe --toplevel`) on latest version 3

for this input:
```js
var styled = require('styled-components');
var Button = styled.button('background-color: #fff');
```
I get this output
```js
require("styled-components").button("background-color: #fff");
```

but when I add `#__PURE__`:
```js
var styled = require('styled-components');
var Button = /*#__PURE__*/ styled.button('background-color: #fff');
```
the output gets blank (so it gets removed).

**Comment by osamajandali** [comment] 2018-01-10 13:49
@Andarist I works just fine, thanks man!

**Comment by osamajandali** [comment] 2018-01-10 13:51
@Andarist I used **version 3.3.5**.
Could you please point me this command documentation on uglifyjs. Thanks again

**Comment by philpl** [comment] 2018-01-10 14:58
@osamajandali I think it's not worth to investigate what happens much further. It'd be more important to add the comment first. Either way, it doesn't hurt to add it, it will only make the output more concise in some cases, whether those will be common or not 😃

**Comment by osamajandali** [comment] 2018-01-10 15:12
@philpl You are right, I have already begin. 
Just curious as I spend some time searching for the solution

**Comment by osamajandali** [comment] 2018-01-11 19:34
I am done with this, I just want to make sure that I did couple of items right before I make the PR.

I have added an option called useUglifyPure which give the user the option to disable it, and it is set true by default.
I have used the package which is provided by babel as @Andarist mentioned.
Do I have to update the snapshots with the new one before the PR or just leave it with the old snapshots?

**Comment by mxstbr** [comment] 2018-01-11 19:42
It'd be great to have tests which verify that it works as expected, but it's definitely not a requirement. Please go ahead and submit your PR, and we'll go from there!

**Comment by osamajandali** [comment] 2018-01-11 20:15
Cool, I will submit the PR now and keeping the old snapshots in order to help the reviewers to see what have changed.

**Comment by Andarist** [comment] 2018-01-11 21:52
> It'd be great to have tests which verify that it works as expected, but it's definitely not a requirement. Please go ahead and submit your PR, and we'll go from there!

Not sure if its worth testing - it would require writing an input fixture, transpiling it with babel, minifying it with uglifyJS probably with some `{ beautify: true, mangle: false }` options and then verifying the output somehow - as snapshot, checking AST or just reading the output as string and doing some indexOf check. Seems quite complicated for minimal gain, would kinda just re-test what uglifyJS should do. IMHO simple fixture/snapshot tests for this should be enough and from what I understand you have already those in place.

**Comment by mxstbr** [comment] 2018-01-12 09:07
> minifying it with uglifyJS probably

I don't care about that. I only want to test that the `#__PURE__` comments are added to the styled calls, i.e. that the Babel plugin does it's job :blush:

**Closed** 2018-01-23 08:24 UTC
Labels: enhancement, help wanted
