### ISSUE TITLE
`cssProp` feature produces invalid CSS with object syntax

### ISSUE THREAD

**Issue by amakk** [styled-components/babel-plugin-styled-components#186] opened 2018-11-30 19:28 UTC
Hi, I'm using the new `css` property, and I noticed that when I upgraded to babel-plugin-styled-components `1.9.2` (from `1.9.0`) it is no longer handling objects in CSS property correctly.

Given this input:

```html
<div css={{ color: 'red' }}>Test</div>
```

I am getting this output: 
```css
.kIHpqD{-webkit-undefinedcolor:red;-ms-flex-undefinedcolor:red;undefinedcolor:red;-webkit-undefined;-ms-flex-undefined;undefined;}
```
and further down: 
```javascript
<div class="my-page___StyledDiv-sc-1f0w8lp-3 kIHpqD">Test</div>
```

I'm expecting it to output the css as something like: 
```css
.kIHpqD{color:red;}
```

If it helps, I'm using `styled-components 4.1.2` with Gatsby via `gatsby-plugin-styled-components 3.0.4`

**Comment by mxstbr** [comment] 2018-12-01 09:52
Hmm, this seems to be a bug, strange. @satya164 I think this was caused by the `requeue`?

**Comment by satya164** [comment] 2018-12-03 10:42
That's pretty weird. No idea why it would add `-webkit-undefined` etc. as prefix. It'll be great if you can create a repro so I can test.

**Comment by mxstbr** [comment] 2018-12-03 17:15
I can replicate this, not sure why this broke.

**Comment by satya164** [comment] 2018-12-03 17:52
Is there a repro somewhere that I can check?

**Comment by satya164** [comment] 2018-12-03 22:18
Can someone please create a repo with the repro?

**Comment by alexlouden** [comment] 2018-12-06 05:34
I'm seeing the same issues after moving from v1.8 with gatsby & rebass:
```js
import { Box } from 'rebass'
<Box p={3} color="blue" css={{ border: "1px solid red" }} {...props} />
```

with babel-plugin-styled-components@1.9.0 & 1.9.1 during `gatsby build`:
```js
  Error: component---src-templates-docstemplate-jsx-d6ef5c80a52750f5e099.js from UglifyJs
  SyntaxError: Unexpected character '`' [component---src-templates-docstemplate-jsx-d6ef5c80a52750f5e099.js:5956,62]
```

and with 1.9.2:
```js
  Module build failed: TypeError: <filepath>.js: Property value expected type of string but got null
```

Basic repro here - doesn't work online but works if you download & run `yarn && yarn start` locally - https://codesandbox.io/s/4z11joq1z7
Can see that the padding (from the `p` prop) and text color (from `color`) are correct, but no red border. See screenshot for css:
![screen shot 2018-12-06 at 1 32 29 pm](https://user-images.githubusercontent.com/1332954/49563601-7f6d2680-f95b-11e8-9588-3c207854c096.png)

**Comment by satya164** [comment] 2018-12-07 18:46
There might be a conflict with the handling of the tagged template literal in the babel plugin as it has special handling I believe. I commented out the `TaggedTemplateExpression` part and it seems to be working. However, I don't have much time to investigate and since no one provided a GitHub repro for me to test on (I have no idea how to tweak the babel config after downloading the codesandbox example), I can't verify right now. If someone has time, try `"transpileTemplateLiterals": false` in the plugin options, or even better, create a repo with the repro.

**Comment by kopax** [comment] 2018-12-08 06:01
I have the same error and wrapping a string using `css` work fine with 1.9.2

**Comment by mxstbr** [comment] 2018-12-10 13:06
I have a potential fix for this in #191, can y'all test this in your app: `npm install babel-plugin-styled-components@experimental`? Let me know whether that fixes the issue or not! :pray:

**Comment by mxstbr** [comment] 2018-12-10 14:35
Found the bug I'm 99% sure: #192

**Closed** 2018-12-10 14:37 UTC
Labels: bug

**Comment by mxstbr** [comment] 2018-12-10 14:38
Please upgrade to v1.9.3, which should fix this issue! If it doesn't please let us know and I'll reopen this. 

```
npm install babel-plugin-styled-components@1.9.3
```

**Comment by mxstbr** [comment] 2018-12-10 14:45
Shoutout to the real MVP @alexlouden! Without your repro I couldn't have found this fix, thanks so much :pray: :pray: :pray: :pray:

**Comment by alexlouden** [comment] 2018-12-11 06:51
No worries! I've updated and it works, thanks so much for the fix!

**Comment by alexlouden** [comment] 2018-12-11 08:22
Oh actually, sorry @mxstbr - I've just noticed the following (on my work project):

```
commons.js:97465 Warning: Invalid attribute name: `_$p_`
    in a (created by ForwardRef)
    in Box (created by ForwardRef)
    in Flex (created by Styled(Flex))
    in Styled(Flex) (at Nav/index.js:22)
    in SectionHeading (at Nav/index.js:69)
```

that line points to a rebass Flex:
```js
  <Flex is="a" alignItems="center" css={{ cursor: 'pointer' }}>
```

Updated the repro repo:
https://github.com/alexlouden/css-prop-bug-repro/commit/03cfc80d19533d326d9cec536177ec66ab0227ed

![screen shot 2018-12-11 at 4 17 42 pm](https://user-images.githubusercontent.com/1332954/49787098-b5961600-fd60-11e8-8cf4-eac6b2b30a96.png)

**Comment by mxstbr** [comment] 2018-12-11 08:32
Hmm yeah this is an issue with rebass passing through all attributes. We might have to rename the generated prop to `css`, let me submit a patch for that 🔜

**Comment by Kovensky** [comment] 2018-12-11 08:32
Oh, wow, that's a fun one.

Rebass implements its own `css` prop by always having a `${props => props.css}` interpolation in all of their components. This gets stolen by the babel plugin, and the way the babel plugin communicates dynamic values to the hoisted styles is with the `_$p_*` props.

_This here is just speculation on my part as I haven't tested/reread the code_, but: Those properties should normally then be filtered out and not passed to the DOM by styled-components, but rebass components are not DOM elements, they're styled-components themselves. As `styled()`ing an already `styled()` component causes it to be adopted rather than nested, this probably triggers the path that passes through properties for composite components, but without triggering the filtering of non-DOM properties that was supposed to happen on the Box component itself (a `styled.div`).

**Comment by mxstbr** [comment] 2018-12-11 08:35
Yes exactly @Kovensky, you are spot on. There is nothing much we can do, but I'll rename the prop to `_css` so it's clear where it comes from!

**Comment by Kovensky** [comment] 2018-12-11 08:37
@mxstbr this is probably just really revealing a bug in `styled-components` core: ```styled(styled.div``)`` ``` should still filter out DOM props, but it's not. Or maybe it is, but it's not when there is even more levels of nesting/adoption.

**Comment by mxstbr** [comment] 2018-12-11 08:38
Not quite, no. It's not `styled(styled.div``)``)`, it's `styled(() => {})`. The lowest-level Rebass component is not a styled component, it's a normal React component that used to handle the `as` and `css` props, so we cannot filter out any props.

**Comment by Kovensky** [comment] 2018-12-11 08:39
Ah, I was looking specifically at `@rebass/grid` as that was the component used in the example. https://github.com/rebassjs/grid/blob/master/src/index.js#L16

**Comment by Kovensky** [comment] 2018-12-11 08:51
Looks like this is a problem with rebass v2; rebass v3 (`rebass@next`) looks like it should be compatible with this.

**Comment by alexlouden** [comment] 2018-12-11 09:01
> Looks like this is a problem with rebass v2; rebass v3 (`rebass@next`) looks like it should be compatible with this.

Thanks for all the debugging! I'm unfortunately stuck on v2 for a little while since v3 is a rather large breaking change - https://github.com/rebassjs/rebass/releases/tag/v3.0.0

The warning doesn't show up for me on 1.8, so I'm happy to stick using that if that makes it easier for you? Then we could ask @jxnblk to add a note to the Rebass v2 docs so others can do the same?
