### ISSUE TITLE
SSR with styled.extend throws error

### ISSUE THREAD

**Issue by srghma** [styled-components/babel-plugin-styled-components#79] opened 2017-08-18 09:25 UTC
[minimal example (its with-styled-component next example)](https://mega.nz/#!o8cESJaC!hy319-Vn5VIfpHeJSteHlR9n0kWFjRMDfevEVAdXbm4)

What I do
1. yarn run dev
2. load page
3. reload page

Get error

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ="1"><div class="sc-bdVaJa iNGvMq" data-
 (server) ="1"><div class="sc-jzJRlG fzsTbP" data-

```

**Comment by mxstbr** [comment] 2017-08-18 12:31
Thanks for the reproduction, appreciated!

**Comment by BjornMelgaard** [comment] 2017-08-18 16:02
@mxstbr will do whatever to get this fixed ;)

**Comment by hmontes** [comment] 2017-08-18 23:02
Same error using this tutorial:

https://medium.com/styled-components/building-a-blog-with-next-js-359cf1236574

**Comment by nialloc9** [comment] 2017-08-25 19:18
Same issue here.

**Comment by fatfisz** [comment] 2017-10-06 11:06
I'd like to tackle this, but first I have to "fix" all the other tests - I'm working on Windows and maybe that somehow contributes to the fact that the ids are different in every case.

<details>

    @@ -1,26 +1,26 @@
     import s from "styled-components";

     const Test = s.div.withConfig({
       displayName: "Test",
    -  componentId: "syqrfc-0"
    +  componentId: "pe3280-0"
     })`width:100%;`;
     const Test2 = true ? s.div.withConfig({
       displayName: "Test2",
    -  componentId: "syqrfc-1"
    +  componentId: "pe3280-1"
     })`` : s.div.withConfig({
       displayName: "Test2",
    -  componentId: "syqrfc-2"
    +  componentId: "pe3280-2"
     })``;
     const styles = { One: s.div.withConfig({
         displayName: "One",
    -    componentId: "syqrfc-3"
    +    componentId: "pe3280-3"
       })`` };
     let Component;
     Component = s.div.withConfig({
       displayName: "Component",
    -  componentId: "syqrfc-4"
    +  componentId: "pe3280-4"
     })``;
     const WrappedComponent = s(Inner).withConfig({
       displayName: "WrappedComponent",
    -  componentId: "syqrfc-5"
    +  componentId: "pe3280-5"
     })``;

      at Object.<anonymous> (test\index.test.js:23:28)
      at handle (node_modules\worker-farm\lib\child\index.js:41:8)
      at process.<anonymous> (node_modules\worker-farm\lib\child\index.js:47:3)
      at emitTwo (events.js:125:13)
      at process.emit (events.js:213:7)
      at handleMessage (internal\child_process.js:753:14)
      at Pipe.channel.onread (internal\child_process.js:472:11)
</details>

**Comment by fatfisz** [comment] 2017-10-06 11:17
That was easy: when calling `'string'.replace(something, other)` only the first occurrence of `something` will be replaced. Will change that to `RegExp` with the `global` flag.

**Comment by philpl** [comment] 2017-10-06 11:48
If there's any new issue with mismatching server/client classnames, please open a new issue, as the root cause has been identifier and fixed by @fatfisz :wink::+1:

**Comment by mxstbr** [comment] 2017-10-06 11:52
Wait I think he just fixed the tests on Windows, not the SSR issue?

**Comment by philpl** [comment] 2017-10-06 12:09
@mxstbr wasn't this the fix? https://github.com/styled-components/babel-plugin-styled-components/pull/92

**Comment by mxstbr** [comment] 2017-10-06 12:14
Yeah but a fix for running the tests on Windows

**Comment by fatfisz** [comment] 2017-10-06 13:37
Yup, sorry for the mess. I should've opened another issue or just not write off-topic info here.

**Comment by fatfisz** [comment] 2017-10-06 16:09
So I think the only problem is with detection. Basically, while it's easy to check that we have ``styled.div` ` `` and that `styled` is imported from styled-components, it's close to impossible to check that ``Compote.extend` ` `` is a candidate for `withConfig` - we don't know if `Compote` is in fact a styled component.

I have a solution, but it looks so awful that I'm not sure it's ok to implement it. It's basically a runtime test:

```js
// Original
Compote.extend`color: hotpink;`

// Transpiled
tryWithConfig(Compote.extend`color: hotpink`, { componentId: '...' })
```

where `tryWithConfig` is a function similar to this:

```js
function tryWithConfig(Component, config) {
  if (isStyled(Component)) {
    return Component.withConfig(config);
  } else {
    return Component;
  }
}
```

In either case we need to pass the metadata somehow. I thought about modifying extend in some way, but it doesn't know about where the extension component is coming from - so if there is `C = A.extend` and `B = A.extend`, the order of importing would influence the outcome.

**Comment by fatfisz** [comment] 2017-10-06 16:20
@philpl I just noticed this comment: https://github.com/styled-components/babel-plugin-styled-components/issues/66#issuecomment-311187106. Could you describe what the changes will be that will enable `withComponent` and `extend` to be handled by the plugin?

**Comment by philpl** [comment] 2017-10-06 16:27
@fatfisz those changes will need some major refactors on the plugin and the library, so don’t worry about them yet ;)

.extend and .withComponent are indeed not detected but we did introduce some code before that modifies the new component’s names deterministically using the old one’s.

Maybe there’s a bug there?

**Comment by philpl** [comment] 2017-10-06 16:32
Found it :)

We’re doing it for withComponent: https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L263

But not extend: https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L285

Also the withComponent componentId generation won’t work for anonymous components (pure functions)

@mxstbr @geelen this actually also explains the ordering bug since the new componentId for styled(styled(PFC)) will be the same (multi dashes are removed) and this the ordering will be messed up!

Sorry for letting the original PR in :(

This will need a major rework

**Comment by fatfisz** [comment] 2017-10-06 16:33
So a quick fix would be possible then?

**Comment by fatfisz** [comment] 2017-10-06 16:34
Anonymous functions are not a problem for me, so passing the componentId in `extend` would be a huge win for me already.

**Comment by philpl** [comment] 2017-10-06 16:34
@fatfisz it won’t be quick but .extend will need to somehow use the rule’s signature to compute a componentId and withComponent will need to ensure that there’s some componentId on the target component

**Comment by philpl** [comment] 2017-10-06 18:29
@fatfisz sure! That’d be amazing

**Comment by fatfisz** [comment] 2017-10-08 22:13
@philpl I overestimated the time that I needed to understand what's going on under the hood and as I'll have even less time during the upcoming week, I won't be able to work on this :(

**Comment by evan-scott-zocdoc** [comment] 2017-11-03 18:02
Is there a plan to tackle this soon @philpl? It happens quite a lot in our projects.

I'd be willing to try and help, but TBH I don't really understand the context of the proposed solution well enough to do an implementation.

**Comment by philpl** [comment] 2017-11-03 19:00
@evan-scott-zocdoc I actually realised that my workaround would not be performant. So we might have to “scrape” at some v3 ideas and wrap all tagged template input in a wrapper that can be produced by a factory function and carries componentId information around with it.

I’m not sure when I’ll have time to work on this unfortunately

**Comment by geelen** [comment] 2017-11-10 01:55
Just caught up on this issue, sorry for my extended absence.

Just to summarise, to see if I'm reading this right, @philpl:

- Deterministic `componentId`s are only being injected at a `styled.*` call, not at `.extend` or `.withComponent` (because the babel plugin has no way of knowing what's a styled component or not)
- As a result, some code was added to generate unique `componentId`s at runtime when you call `withComponent`, which happens to clash with... some other styles causing an ordering bug? (this bit I'm not clear on)
- If `.extend` and `.withComponent` were able to be picked up by the babel plugin, this problem would go away?

It seems to me that `.extend` is being used a lot more than I ever thought it would—the problem of "when do I use `styled(X)` vs `X.extend`" (the latter being potentially a runtime error if `X` isn't an SC) comes up a fair bit. Potentially that API is just bad.

My gut reaction is to have `.extend` and `.withComponent` _not_ introduce a new `componentId`. After all, component IDs are useful for contextual overrides and.... not much else? So the only case that would fail would be:

```js
const X = styled.div` ... `
const Y = X.extend` ... `

const Z = styled.div`
  color: red;
  ${ Y } {
    color: black;
  }
`
```

The weirdness would be that, in the above example, `<X><Z/></X>` would render black. That might be a bit unexpected, sure, but I don't know if it's a dealbreaker. After all, you could always write `const Y = styled(X)` instead. But still something feels a bit off, so I'm not sure it's a good option.

I think the problem comes from the syntax `const Y` `=` `X.extend`. It makes it feel like `Y` and `X` should have no continuing relationship after the point of extension. I wonder, then, what people are actually using `.extend` for, and whether there's a better way to represent it.

Consider this, instead:

```
const X = styled.div` ... `
X.addVariant('Y')` ... ` // works just like extend

const Z = styled.div`
  color: red;
  ${ X.Y } {
    color: black;
  }
`
```

Something like this could entirely replace `.extend` by instead allowing someone to add "variants" to an SC, which would then be made available as a property on the originating SC. Now, there's no way to access `Y` in isolation—it's obviously intrinsically linked to `X`. But better than that, we have a key "Y" that we can use to deterministically combine with the parent's `componentId`, so the problem goes away. Right?

For the moment, we could just advice everyone to use `styled(X)` instead of `.extend`?

**Comment by evan-scott-zocdoc** [comment] 2017-11-10 01:56
I'm very much in favor of dropping `.extend` entirely. It's confusing.

**Comment by philpl** [comment] 2017-11-10 02:46
@geelen I do think that the point of extend is to create another component that *happens* to be a subset of the new one, and like you said:

> It makes it feel like Y and X should have no continuing relationship after the point of extension

Which they indeed don't. I feel like the biggest side effect of introducing `.extend` (and not being clear enough that styled(X) should be avoided as often as possible), indicates to most that this is a pattern that should be commonly used.

At the same time the variant suggestion seems really pointless to me. We've always tried to promote two patterns here: Inheritance with extend and Composition using mixins. But when I've talked to @kof we arrived at an interesting conclusion through a misunderstanding actually.

Since extend doesn't continue to have a relationship to the parent component, it's indeed just composition again, but with an unnecessarily unintuitive API.

And I think, luckily, we have the solution right here: https://github.com/styled-components/styled-components/issues/1209#issuecomment-334563612 (some of the later composition suggestions are mostly unrelated)

So extend could also be represented as:

```js
const Parent = styled.div`
  color: palevioletred;
`

const Child = styled.div`
  ${Parent.styles}
  background: papayawhip;
`
```

So in this case we'd define Parent.styles to be the exact input that was passed to styled.div to create it, i.e. the tagged template literal arguments. This would work no matter how we'd change the actual input for the component.

The huge advantage, imho, is that this makes it way easier to learn styled-components for future users: There's only one tool of choice and it's composition through interpolations. Be it with mixins, or the above pattern.

**Comment by geelen** [comment] 2017-11-10 05:40
Oh yeah that's way better. My "variant" stuff is just that I've seen people using like:

```js
const Button = styled.button` ... `
const PrimaryButton = Button.extend` ... `
const DangerousButton = Button.extend` ... `
```

Instead of defining a `Button` with props `primary` and `button`. It's also why I've been playing around with weird pre-compiled syntax like this:

```js
const Button = styled.button`
  ...

  $props.primary {
    ...
  }

  $props.dangerous {
    ...
  }
`
```

Each of those would compile `$props.x { ... }` to ``${ props => props.x && css` ... ` }``. Basically a shorthand to get people to start thinking about using to SC to generate a single component with variations rather than a factory for multiple, similar components.

So I think I got my wires crossed, `addVariant` is a bad idea, `${Parent.styles}` is much better (though **`${Parent.rules}`** would be a better name IMO).

So let's deprecate `.extend` in the next major?

**Comment by geelen** [comment] 2017-11-10 05:58
> (and not being clear enough that styled(X) should be avoided as often as possible)

Also, on this, why is this? I'm kinda of the opposite opinion, that `styled(X)` is better than `X.extends` in almost all cases... 🤷‍♂️

**Comment by probablyup** [comment] 2017-11-10 06:02
I’ve asked similar questions a few times and the consensus seems to be favoring the Unix model of API design: specific, simple methods without overloading.

Agreed that simplicity is a worthy goal, but I disagree that it’s right to sacrifice DX for it, especially when many people are on record saying it’s confusing.

**Comment by geelen** [comment] 2017-11-10 06:05
Sorry, I'm a bit confused. Which do you prefer?

**Comment by probablyup** [comment] 2017-11-10 06:07
Only `styled(x)`

**Comment by morajabi** [comment] 2017-11-10 08:00
@geelen That's a bit funny (no offence) since I wrote an FAQ with @philpl here on this: https://www.styled-components.com/docs/faqs#when-should-i-use-
And we are encouraging users to use `.extends` whenever it's a styled component. Also, we do not recommend to use `styled()` on our own components and thus whenever we can not use `.extend` try to use either dynamic styling with props or writing a `Wrapper` component around it. To leave `styled()` only for external components. That way we won't be confused in our own styles and they'll remain somehow pure and idiomatic to SC.

**Comment by philpl** [comment] 2017-11-10 11:51
I think since we don’t even agree internally on how to recommend it, it’s a fair assumption that the entire approach is flawed

**Comment by mxstbr** [comment] 2017-11-10 11:51
Agreed.

**Comment by morajabi** [comment] 2017-11-10 12:27
Actually, I remember when v2 was released I couldn't quite understand what is the expected behaviour of `.extend`. Although I pretty didn't fear to use for example `withComponent` I didn't use extend at all until I saw a few examples. I think the act of extending is not a bad thing or confusing but what is confusing is either naming or the way API is designed (which users can't understand whether the two Comp have relations or not).

**Comment by ghengeveld** [comment] 2017-11-20 12:12
I found this as a workaround to avoid using `.extend`. Instead of:

```js
const SearchButton = Button.extend`
  color: palevioletred;
`

<SearchButton type="submit" />
```

Use this:

```js
const SearchButton = styled.div`
  button {
    color: palevioletred;
  }
`

<SearchButton>
  <Button type="submit" />
</SearchButton>
```

Essentially you wrap the Component to be extended in another component, and target the inner element using a regular CSS selector.

**Comment by geelen** [comment] 2017-11-21 04:45
That'll work! But you might want to make it `> button { color: palevioletred; }` to target `button` elements _only one level deep_. Otherwise you might get some spooky-action-at-a-distance.

You can also use the `Button` styled component in this way, too:

```js
const SearchButton = styled.div`
  > ${ Button } {
    color: palevioletred;
  }
`
```

That way you're targeting _only_ your `Button` component, not any html `<button>`

But yep, plenty of different options 👍

**Comment by ckeeney** [comment] 2018-04-13 18:59
Given the issues with SSR and `.extend`, I think a note should be added to the [When should I use `styled()` FAQ page](https://www.styled-components.com/docs/faqs#when-should-i-use-styled).  Right now, the answer contains

> We recommend to use `.extend` where possible for internal `StyledComponents`

and

> Keep in mind that wrapping your own components with `styled()` is not recommended.

I see this FAQ page mentioned a few months ago above, https://github.com/styled-components/babel-plugin-styled-components/issues/79#issuecomment-343401444, but it still hasn't been changed.

Is this no longer the recommended approach?

I use not only `extend`, but also `extend.attrs()` fairly extensively and I have quite a bit of code that looks like this:

```js
const StyledNavLink = Text.extend.attrs({
    color: 'white',
    fontWeight: 600,
    fontFamily: 'sans2',
    fontSize: 0,
    mx: '6px',
    uppercase: true
})``;
```

Is there any workaround for getting server side rendering working without refactoring all of this to use `styled` and creating wrappers to pass in these additional props?

**Comment by dntrkv** [comment] 2018-07-25 20:44
@ckeeney Agreed. I have wasted hours trying to figure this issue out. There are so many potential issues that can cause the client/server markup mismatch, it would great to update the styled-components docs warning users of this limitation.

**Closed** 2021-06-29 20:44 UTC
Labels: bug
