### ISSUE TITLE
Upgrading to 1.5.0 makes displayNames in snapshots differ on Linux vs OS X

### ISSUE THREAD

**Issue by dgcoffman** [styled-components/babel-plugin-styled-components#124] opened 2018-01-25 00:01 UTC
After upgrading to 1.5.0 from 1.1.7, our Linux builds take about 3 times as long and fail because some component displayNames differ vs our OSX local dev.

Example of difference is: previously a component would have displayName  `Flex__Flex` and now it has `Flex`.

Maybe a clearer way to say this: In our node-v8.2.1-linux-x64 build machine, upgrading from 1.1.7 to 1.5.0 changes the displayNames of some components from "Name__Name" to just "Name". Wouldn't be an issue, except this change _does not_ manifest on our OSX dev machines.

Sorry for not super actionable issue. 

Putting out feelers for others who had this issue and can advise.

**Comment by philpl** [comment] 2018-01-25 01:37
https://github.com/styled-components/babel-plugin-styled-components/releases/tag/v1.2.0

> Example of difference is: previously a component would have displayName Flex__Flex and now it has Flex.

1.2.0 introduced a slightly modified hashing strategy so this is completely expected behaviour :wink:

> this change does not manifest on our OSX dev machines.

This seems odd however; Are you sure you have the **exact** same versions (lockfiles?) on all machines.

Also please note that 1.2.0 is a tandem release with SC 2.4.0, so please make sure both match https://github.com/styled-components/styled-components/releases/tag/v2.4.0

**Comment by dgcoffman** [comment] 2018-01-29 22:22
Thanks @philpl you were right, I _did_ have SC 2.2.1 before!

Bad news is that after getting on the latest versions, my issue persists.

As of this morning I have in my package.json:
<img width="1270" alt="screen shot 2018-01-29 at 2 20 37 pm" src="https://user-images.githubusercontent.com/1711204/35537603-a841a4ce-04ff-11e8-929f-b0f94866fe5f.png">

and yarn.lock requires those same versions.

Our test failures in CircleCI look like
```
    - <FormGroup__FormGroup>
    + <FormGroup>

    - <StatusIndicator__StatusIndicator
    + <StatusIndicator

    - <Circle__Circle
    + <Circle

    and so on...
```

In addition, and perhaps more worrysome, running our unit test suite now takes roughly 14 minutes, up from 4 minutes.

No change in execution time or displayNames running locally. Any other ideas?

**Comment by dgcoffman** [comment] 2018-01-29 22:47
Here's what I've tried so far:

<img width="923" alt="screen shot 2018-01-29 at 2 46 37 pm" src="https://user-images.githubusercontent.com/1711204/35538569-424b55ee-0503-11e8-817e-afed84d54624.png">

**Comment by dgcoffman** [comment] 2018-01-29 23:39
`"minify": false` seems make the behavior consistent

**Comment by probablyup** [comment] 2018-05-09 05:56
@dgcoffman the build performance degradation might be from the uglify pure comments that we added and then disabled a few months ago. Could you try `1.5.1` and let me know how it looks?

**Comment by TheRickTM** [comment] 2018-08-31 21:34
We recently upgraded to `1.6.0` along with `styled-components`: `3.4.5` and are experiencing the exact same issues. We upgraded from `1.5.1` and `3.2.5`. Running tests locally on OSX returns different names as previously reported. The solution to turn off minify works but significantly decreases performance, up to 3x. 

```
    - .c41 .form_component__StyledError-sc-14ivdot-2 {
    + .c41 .form_component__StyledError-cGUtYm {
```

**Comment by probablyup** [comment] 2018-08-31 21:39
Yup we did make a change to shorten the generated names a bit. We don't make any guarantees that the hashing output will be consistent from one library version to the next, but they will be consistent for the same version.

**Comment by probablyup** [comment] 2018-08-31 21:41
As far as performance goes, I'm not sure. We disabled the uglifyPure functionality in 1.5.1 I believe and removed it in 1.6, so the perf should be mostly consistent with 1.4.

**Comment by TheRickTM** [comment] 2018-08-31 21:42
Thanks for the quick response. But this output is for the same version. 

```- .c41 .form_component__StyledError-sc-14ivdot-2 {```
was generated from our linux docker container we use for testing

```+ .c41 .form_component__StyledError-cGUtYm {```
was generated from my development OS X machine.

Both have the same exact versions of the libraries installed when executing the tests. The output is consistent, just varies on operating system it appears.

**Comment by probablyup** [comment] 2018-08-31 21:44
@TheRickTM is the bundle being built inside the docker container? The filesystems need to be consistent for the built hashes to be equivalent.

**Comment by probablyup** [comment] 2018-08-31 21:46
The reason for that is the hash is based on your project name + file path: https://github.com/styled-components/babel-plugin-styled-components/blob/e92539966d9edddb22fe216c2e6573de8ab61e89/src/visitors/displayNameAndId.js#L95-L108

**Comment by TheRickTM** [comment] 2018-08-31 21:54
@probablyup, thanks for the detailed information. That is what is causing our issue. I'll see what we can do to work around this and configure the development environments to match our docker container's file system pathing. Is there a possibility in the future for this to be configurable? File path on the file system seems like it could have lots of variation based on each developers preferences.

**Comment by probablyup** [comment] 2018-08-31 21:55
So what we did at Zocdoc is we built everything during CI in the same environment and then copied the bundle into the docker container for use. That way everything is assembled in a "clean room" I guess you could say. Is that a viable strategy for your setup?

**Comment by TheRickTM** [comment] 2018-08-31 22:10
We have the same "clean room" setup as you are describing. The test perform over 50% faster outside of the container which is the reason for the interest in being able to run them locally. The container is the source of truth as that is where we build all of our environments from. So we can look into getting the developers to setup the same file system path if they want to run it locally. 

Is there any reason the hash needs to use the full path to the file, instead of relative to the project?

**Comment by probablyup** [comment] 2018-09-01 01:12
It is a relative path.

**Comment by TheRickTM** [comment] 2018-09-04 13:39
@probablyup thanks for your help. I missed the relative part. After updating to the latest `jest-styled-components` the issue has been resolved.

**Comment by probablyup** [comment] 2018-09-04 16:31
Oh interesting. I'm not a contributor to that subproject so curious what they did... Should I close this issue?

**Comment by TheRickTM** [comment] 2018-09-04 17:35
The subproject renames the styled components `c0`...`cn` for jest snapshots. This prevents any changes in the hashing that would cause the snap to break. We were using previously but hadn't updated to the latest which detected the new changes and resolved. It records the styles as well for us so they can be compared for any changes in display as well.

Thanks again for the assistance.

**Closed** 2019-06-25 02:01 UTC
Labels: bug
